In [2]:
import numpy as np

In [38]:
a=np.array([1,2,3,4,5])
print(a)
print(a[-1])

[1 2 3 4 5]
5


In [4]:
b=np.array([ [1,2,3],[4,5,6] ])
print(b)

[[1 2 3]
 [4 5 6]]


In [12]:
c=np.array([[[1,2],[3,4]]
            ,[[5,6],[7,8]]
            ,[[12,13],[14,15]]])
print(c)
print(c.ndim)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[12 13]
  [14 15]]]
3


In [9]:
arr=np.ones((3,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [8]:
import numpy as np
arr=np.zeros((3,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [10]:
print(arr.ndim)

2


In [16]:
arr=np.linspace(0,10,7)
print(arr)

[ 0.          1.66666667  3.33333333  5.          6.66666667  8.33333333
 10.        ]


In [66]:
arr=np.arange(1,102)
print(arr)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100 101]


In [35]:
c=np.array([[[1,2],[3,4]]
            ,[[5,6],[7,8]]
            ,[[12,13],[14,15]]])
print(c.size)
print(c.shape)
print(c.ndim)
print(c.dtype)

12
(3, 2, 2)


In [37]:
c=np.array([[[1,2],[3,4]]
            ,[[5,6],[7,8]]
            ,[[12,13],[14,15]]])
print(c.dtype)

int64


In [46]:
c=np.array([1,2,3,4,5])
print(c[:3])
print(c[1:5])
print(c[ 2:])

[1 2 3]
[2 3 4 5]
[3 4 5]


In [60]:
b=np.array([ [1,2,3],[4,5,6] ])
print(b[:1])
print(b[0,:2])
print(b[1,:-1])

[[1 2 3]]
[1 2]
[4 5]


In [47]:
arr=np.eye(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [10]:
arr=np.arange(1,13)
newarr=arr.reshape(3,4)
print(newarr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [1]:
import pandas as pd

In [3]:
s=pd.Series([1,2,3,4])
print(s)

0    1
1    2
2    3
3    4
dtype: int64


In [37]:
s=pd.Series([10,34,543,234,44])
print(s)
print('min =',s.min())
print('max =',s.max())
print('sum =',s.sum())
print('mean =',s.mean())

0     10
1     34
2    543
3    234
4     44
dtype: int64
min = 10
max = 543
sum = 865
mean = 173.0


In [5]:
data={
    'roll no':101,
    'dept':'CS with AI',
    'Score':57
}
s=pd.Series(data)
print(s)

roll no           101
dept       CS with AI
Score              57
dtype: object


In [40]:
data={
    'roll no':[101,102,103],
    'dept':['CS with AI','CS','DS'],
    'Score':[57,99,45]
}
s=pd.DataFrame(data)
print(s)


   roll no        dept  Score
0      101  CS with AI     57
1      102          CS     99
2      103          DS     45


In [31]:

s=pd.DataFrame(data,index=['A1','B2','C3'])
print(s)
print(s[['roll no','Score']])
print(s.columns)
print(s.dtypes)
print(s.index)
print(s.loc['A1'])
print(s.loc[['A1','B2']])

    roll no        dept  Score
A1      101  CS with AI     57
B2      102          CS     99
C3      103          DS     45
    roll no  Score
A1      101     57
B2      102     99
C3      103     45
Index(['roll no', 'dept', 'Score'], dtype='object')
roll no     int64
dept       object
Score       int64
dtype: object
Index(['A1', 'B2', 'C3'], dtype='object')
roll no           101
dept       CS with AI
Score              57
Name: A1, dtype: object
    roll no        dept  Score
A1      101  CS with AI     57
B2      102          CS     99


In [56]:
s['grade']=['A','A+','C']
print(s)
print(s.iloc[0])
print(s.iloc[[0,1]])


   roll no        dept  Score grade
0      101  CS with AI     62     A
1      102          CS    104    A+
2      103          DS     50     C
roll no           101
dept       CS with AI
Score              62
grade               A
Name: 0, dtype: object
   roll no        dept  Score grade
0      101  CS with AI     62     A
1      102          CS    104    A+


In [57]:
s['Score']=s['Score']+5
print(s)

   roll no        dept  Score grade
0      101  CS with AI     67     A
1      102          CS    109    A+
2      103          DS     55     C


In [59]:
s.drop('grade',
      axis=1,
      inplace=True)


In [60]:
print(s)

   roll no        dept  Score
0      101  CS with AI     67
1      102          CS    109
2      103          DS     55


In [64]:
print(s['Score'].sum())
print(s['Score'].max())
print(s['Score'].min())
print(s['Score'].mean())

231
109
55
77.0


In [2]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)

[5 7 9]


In [6]:
a=np.array([10,20,30,40])
print(np.sum(a))
print(np.mean(a))
print(np.max(a))
print(np.min(a))
print(np.std(a))

100
25.0
40
10
11.180339887498949


In [9]:
a=np.array([1,2,3,4,5,6,7,8,9,10])
print(a.dtype)
print(a.size)

int64
10


In [12]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(matrix)

print(matrix[0])

print(matrix[-1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
[7 8 9]


In [25]:
arr=np.arange(1,21)
print(arr)
print(arr[:10])
print(arr[14:])
print(list(range(1, 20, 2)))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 1  2  3  4  5  6  7  8  9 10]
[15 16 17 18 19 20]
[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]


In [28]:
arr=np.arange(1,13)
print(arr)
print(arr.reshape(3,4))
print(arr.reshape(2,6))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [33]:
s=np.array([ [1,2,3],[4,5,6] ])
print('min =',s.min())
print('max =',s.max())
print('sum =',s.sum())
print('mean =',s.mean())


min = 1
max = 6
sum = 21
mean = 3.5


In [2]:
a=pd.read_csv("student.csv")
print(a)

   RollNo    Name  Department  Marks
0     101    Arun  CS wtih AI     90
1     102  Mohana          CS    100
2     103  Kumari          CA     99
3     104  Deepak       B Com     97


In [18]:
print(a.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   RollNo      4 non-null      int64 
 1   Name        4 non-null      object
 2   Department  4 non-null      object
 3   Marks       4 non-null      int64 
dtypes: int64(2), object(2)
memory usage: 260.0+ bytes
None


In [17]:
a.describe()

,RollNo,Marks
count,4.000000,4.00000
mean,102.500000,96.50000
std,1.290994,4.50925
min,101.000000,90.00000
25%,101.750000,95.25000
50%,102.500000,98.00000
75%,103.250000,99.25000
max,104.000000,100.00000


In [22]:
print(a.columns)

Index(['RollNo', 'Name', 'Department', 'Marks'], dtype='object')


In [13]:
print(a.head())

   RollNo    Name  Department  Marks
0     101    Arun  CS wtih AI     90
1     102  Mohana          CS    100
2     103  Kumari          CA     99
3     104  Deepak       B Com     97


In [14]:
print(a.head(2))

   RollNo    Name  Department  Marks
0     101    Arun  CS wtih AI     90
1     102  Mohana          CS    100


In [15]:
print(a.tail(2))

   RollNo    Name Department  Marks
2     103  Kumari         CA     99
3     104  Deepak      B Com     97


In [16]:
print(a.iloc[2])

RollNo           103
Name          Kumari
Department        CA
Marks             99
Name: 2, dtype: object


In [2]:
arr=[10,20,30,40,50]
for element in arr:
    print(element)

10
20
30
40
50


In [4]:
arr=[11,22,33,44,55]
arr[3]=21
print(arr)

[11, 22, 33, 21, 55]


In [6]:
arr=[1,2,3,4,5]
arr.insert(2,30)
print(arr)

[1, 2, 30, 3, 4, 5]


In [7]:
arr=[10,20,30,40,50]
arr.remove(40)
print(arr)

[10, 20, 30, 50]


In [8]:
arr=[10,20,30,40,50]
key=40
if key in arr:
    print("element found")
else:
    print("element not found")

element found


In [16]:
arr=[10,30,20,50,40]
arr.sort()
print(arr)

[10, 20, 30, 40, 50]


In [18]:
arr=[11,33,44,55,56,76,]
print(arr[3])
print(arr[5])

55
76


In [4]:
class Mystack:
    def __init__(self,cap):
        self.capacity=cap
        self.arr=[0]*self.capacity
        self.top=-1

        def push(self,x):
            if self.top==self.capacity-1:
                print("stack overflow")
                return
            self.top+=1
            self.arr[self.top]=x

        def pop(self):
            if self.top==-1:
                print("stack underflow")
                return -1
            val=self.arr[self.top]
            self.top-=1
            return val

        def peek(self):
            if self.top==-1:
                print("stack is empty")
                return -1
            return self.arr[self.top]

        def isEmpty(self):
            return self.top==-1

        def isFull(self):
            return
        self.top==self.capacity-1

        if __name__=="__main__":
            size=int(inpit("enter the size of the stack"))

            st=Mystack(size)

            n=int(input("enter the number of elements to push:"))

            for i in range(n):
                x=int(input(f"enter element{i+1}:"))
                st.push(x)

            print("Popped:",st.pop())

            print("Top element:",st.peek())

            print("Is stack empty:","Yes"if st.isEmpty() else"No")

            print("Is stack full:","Yes"if st.isFull() else"No")

        

In [16]:
class Mystack:
    def __init__(self,cap):
        self.capacity=cap
        self.arr=[0]*self.capacity
        self.top=-1

    def push(self,x):
        if self.top==self.capacity-1:
            print("stack overflow")
            return
        self.top+=1
        self.arr[self.top]=x

    def pop(self):
        if self.top==-1:
            print("stack underflow")
            return -1
        val=self.arr[self.top]
        self.top-=1
        return val

    def peek(self):
        if self.top==-1:
            print("stack is empty")
            return -1
        return self.arr[self.top]

    def isEmpty(self):
        return self.top==-1

    def isFull(self):
        return self.top==self.capacity-1

Size=int(input("enter the size of the stack"))

st=Mystack(Size)

n=int(input("enter the number of elements to push:"))

for i in range(n):
    x=int(input(f"enter element{i+1}:"))
    st.push(x)

print("Popped:",st.pop())

print("Top element:",st.peek())

print("Is stack empty:","Yes"if st.isEmpty() else"No")

print("Is stack full:","Yes"if st.isFull() else"No")

        

enter the size of the stack 6
enter the number of elements to push: 5
enter element1: 10
enter element2: 20
enter element3: 30
enter element4: 40
enter element5: 50


Popped: 50
Top element: 40
Is stack empty: No
Is stack full: No


In [9]:
class Node:
    def __init__(self, x):
        self.data = x
        self.next = None


class MyStack:
    def __init__(self):
        self.top = None
        self.count = 0

    def push(self, x):
        temp = Node(x)
        temp.next = self.top
        self.top = temp
        self.count += 1

    def pop(self):
        if self.top is None:
            print("Stack Underflow")
            return -1

        temp = self.top
        self.top = self.top.next
        self.count -= 1
        return temp.data

    def peek(self):
        if self.top is None:
            print("Stack is empty")
            return -1

        return self.top.data

    def isEmpty(self):
        return self.top is None

    def size(self):
        return self.count


# Driver code
st = MyStack()

n = int(input("Enter the number of elements to push: "))

for i in range(n):
    x = int(input(f"Enter element {i + 1}: "))
    st.push(x)

print("Popped:", st.pop())
print("Top element:", st.peek())
print("Is stack empty:", "Yes" if st.isEmpty() else "No")
print("Current size:", st.size())

Enter the number of elements to push:  3
Enter element 1:  10
Enter element 2:  22
Enter element 3:  33


Popped: 33
Top element: 22
Is stack empty: No
Current size: 2


In [5]:
def prec(c):
    if c=='^':
        return 3
    elif c=='/' or c=='*':
        return 2
    elif c=='+' or c=='-':
        return 1
    else:
        return -1
def isRightAssociative(c):
    return c=='^'
def infixToPostfix(s):
    st=[]
    res=[]
    for c in s:
        if('a' <=c<= 'z') or ('A' <=c<= 'Z')  or ('0' <=c<= '9') :
            res.append(c)
        elif c=='(':
            st.append('(')
        elif c==')':
            while st and st[-1]!='(':
                res.append(st.pop())
            st.pop()

        else:
            while st and st[-1]!='(' and (
                prec(st[-1]) > prec(c) or
                (prec(st[-1]) == prec (c) and not isRightAssociative(c))
            ):
                res.append(st.pop())
            st.append(c)
    while st:
        res.append(st.pop())
    return ''.join(res)
if __name__=="__main__":
    exp = "a*(b+c)/d"
    print(infixToPostfix(exp))

abc+*d/
